/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as EnergyImport } from "./routes/energy";
import { Route as IndexImport } from "./routes/index";
import { Route as MoodImport } from "./routes/mood";

// Create/Update Routes

const MoodRoute = MoodImport.update({
	id: "/mood",
	path: "/mood",
	getParentRoute: () => rootRoute,
} as any);

const EnergyRoute = EnergyImport.update({
	id: "/energy",
	path: "/energy",
	getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexImport;
			parentRoute: typeof rootRoute;
		};
		"/energy": {
			id: "/energy";
			path: "/energy";
			fullPath: "/energy";
			preLoaderRoute: typeof EnergyImport;
			parentRoute: typeof rootRoute;
		};
		"/mood": {
			id: "/mood";
			path: "/mood";
			fullPath: "/mood";
			preLoaderRoute: typeof MoodImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/energy": typeof EnergyRoute;
	"/mood": typeof MoodRoute;
}

export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/energy": typeof EnergyRoute;
	"/mood": typeof MoodRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	"/": typeof IndexRoute;
	"/energy": typeof EnergyRoute;
	"/mood": typeof MoodRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/energy" | "/mood";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/energy" | "/mood";
	id: "__root__" | "/" | "/energy" | "/mood";
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	EnergyRoute: typeof EnergyRoute;
	MoodRoute: typeof MoodRoute;
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	EnergyRoute: EnergyRoute,
	MoodRoute: MoodRoute,
};

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/energy",
        "/mood"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/energy": {
      "filePath": "energy.tsx"
    },
    "/mood": {
      "filePath": "mood.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
